[tool.poetry]
name = "zimmy"
version = "0.1.0"
description = ""
authors = ["zimmy <holden@upstage.ai>"]

[tool.poetry.dependencies]
python = "^3.8"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
